app:
    build: .
    command: python3 -u app.py
    ports: 
        - "5000:5000"
    links:
        - db
db:
    image: mongo:latest
    hostname: mongodb
    ports:
        - 27017:27017
    environment:
        - MONGO_INITDB_DATABASE=pythonmongodb
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=password
    
     
    
   
        